// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// App
export const LOADING_STATE = "LOADING_STATE";
export const DRAWER_STATE = "DRAWER_STATE";
export const SNACKBAR_STATE = "SNACKBAR_STATE";
